# Form implementation generated from reading ui file 'c:\Users\mikuk\Documents\yr2gp\greenwood\greenwood\windows\ui\AW.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


